// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CynclyTrainingMVC5.Models;

public partial class Group
{
    public int GroupID { get; set; }

    public string Groups { get; set; }

    public string GroupName { get; set; }

    public string Remarks { get; set; }
}