// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalWebAPITasks8.Models;

public partial class OfficialTask
{
    public int TaskId { get; set; }

    public string TaskName { get; set; }

    public DateOnly TaskDate { get; set; }

    public string TaskStatus { get; set; }

    public string Remark { get; set; }
}